<?php

namespace AppBundle\Repository;

/**
 * AsistenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistenciasRepository extends \Doctrine\ORM\EntityRepository
{
}
