<?php

namespace AppBundle\Repository;

/**
 * AssistsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistsRepository extends \Doctrine\ORM\EntityRepository
{
}
