<?php

namespace AppBundle\Repository;

/**
 * EquiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquiposRepository extends \Doctrine\ORM\EntityRepository
{
}
