<?php

namespace AppBundle\Repository;

/**
 * GoalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalsRepository extends \Doctrine\ORM\EntityRepository
{
}
