<?php

namespace AppBundle\Repository;

/**
 * GolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GolesRepository extends \Doctrine\ORM\EntityRepository
{
}
