<?php

namespace AppBundle\Repository;

/**
 * MinutosJugadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinutosJugadosRepository extends \Doctrine\ORM\EntityRepository
{
}
