<?php

namespace AppBundle\Repository;

/**
 * TarjetasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarjetasRepository extends \Doctrine\ORM\EntityRepository
{
}
